"""add postgre

Revision ID: 405102e7d90b
Revises: 
Create Date: 2025-04-23 05:49:30.782324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405102e7d90b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('received_time', sa.DateTime(), nullable=False),
    sa.Column('model_time_seconds', sa.Float(), nullable=False),
    sa.Column('body_part', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('prediction', sa.String(), nullable=False),
    sa.Column('fracture_confidence', sa.Float(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
